//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialType
    {
        public int Id { get; set; }
        public string MaterialType1 { get; set; }
        public decimal PercentWithoutMistakes { get; set; }
    }
}
