//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class databaseEntities : DbContext
    {
        private static databaseEntities _context;
        public databaseEntities()
            : base("name=databaseEntities")
        {
        }

        public static databaseEntities GetContext()
        {
            if (_context == null)
            {
                _context = new databaseEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<City> City { get; set; }
        public DbSet<House> House { get; set; }
        public DbSet<Index> Index { get; set; }
        public DbSet<MaterialType> MaterialType { get; set; }
        public DbSet<Partner> Partner { get; set; }
        public DbSet<PartnerAdress> PartnerAdress { get; set; }
        public DbSet<PartnerName> PartnerName { get; set; }
        public DbSet<PartnerProducts> PartnerProducts { get; set; }
        public DbSet<PartnerType> PartnerType { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<ProductType> ProductType { get; set; }
        public DbSet<Street> Street { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
