//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public PartnerProducts()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PartnerNameId { get; set; }
        public int ProductAmount { get; set; }
        public System.DateTime SellDate { get; set; }
    
        public virtual PartnerName PartnerName { get; set; }
        public virtual ICollection<Products> Products { get; set; }
    }
}
