//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerAdress
    {
        public PartnerAdress()
        {
            this.Partner = new HashSet<Partner>();
        }
    
        public int Id { get; set; }
        public int IndexId { get; set; }
        public int AreaId { get; set; }
        public int CityId { get; set; }
        public int StreetId { get; set; }
        public int HouseId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual City City { get; set; }
        public virtual House House { get; set; }
        public virtual Index Index { get; set; }
        public virtual ICollection<Partner> Partner { get; set; }
        public virtual Street Street { get; set; }
    }
}
