//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerName
    {
        public PartnerName()
        {
            this.Partner = new HashSet<Partner>();
            this.PartnerProducts = new HashSet<PartnerProducts>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Partner> Partner { get; set; }
        public virtual ICollection<PartnerProducts> PartnerProducts { get; set; }
    }
}
