//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int Id { get; set; }
        public int PartnerTypeId { get; set; }
        public int PartnerNameId { get; set; }
        public string DirectorLastName { get; set; }
        public string DirectorFirstName { get; set; }
        public string DirectorMiddleName { get; set; }
        public string Email { get; set; }
        public string PartnerPhone { get; set; }
        public int PartnerAdressId { get; set; }
        public string INN { get; set; }
        public int Rating { get; set; }
    
        public virtual PartnerAdress PartnerAdress { get; set; }
        public virtual PartnerName PartnerName { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
